
import { LocalNotifications } from '@capacitor/local-notifications';
import { Capacitor } from '@capacitor/core';

export const MOTIVATIONAL_MESSAGES = [
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "Success isn't given. It's earned in the gym.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Every workout is progress. Every rep counts.",
  "Champions train, losers complain.",
  "Your only competition is who you were yesterday.",
  "Sweat is just fat crying.",
  "Don't wish for it, work for it.",
  "The gym doesn't care about your excuses.",
  "Strong people don't put others down. They lift them up.",
  "Your body achieves what your mind believes.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "The only bad workout is the one that didn't happen.",
  "Push yourself because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "The hardest lift of all is lifting your butt off the couch.",
  "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.",
  "A one hour workout is only 4% of your day. No excuses.",
  "The groundwork for all happiness is good health.",
  "Take care of your body. It's the only place you have to live.",
  "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.",
  "The successful warrior is the average person with laser-like focus.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Your limitation—it's only your imagination.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little progress is still progress.",
  "What seems impossible today will one day become your warm-up.",
  "If you're tired of starting over, stop giving up.",
  "The miracle isn't that I finished. The miracle is that I had the courage to start.",
  "A healthy outside starts from the inside.",
  "Those who think they have not time for bodily exercise will sooner or later have to find time for illness.",
  "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.",
  "The reason I exercise is for the quality of life I enjoy.",
  "To enjoy the glow of good health, you must exercise.",
  "Exercise should be regarded as tribute to the heart.",
  "The first wealth is health.",
  "He who conquers others is strong; He who conquers himself is mighty.",
  "Lack of activity destroys the good condition of every human being, while movement and methodical physical exercise save it and preserve it.",
  "A man's health can be judged by which he takes two at a time - pills or stairs.",
  "Exercise is a celebration of what your body can do. Not a punishment for what you ate.",
  "Take control of your consistent emotions and begin to consciously and deliberately reshape your daily experience of life.",
  "The pain of discipline weighs ounces while the pain of regret weighs tons.",
  "You don't have to be extreme, just consistent.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "The only person you are destined to become is the person you decide to be.",
  "Health is a state of complete harmony of the body, mind and spirit.",
  "Fitness is like a relationship. You can't cheat and expect it to work.",
  "Your body can do it. It's your mind you need to convince.",
  "The best project you'll ever work on is you.",
  // Continue with more motivational messages...
  "Rome wasn't built in a day, but they were laying bricks every hour.",
  "You are what you repeatedly do. Excellence is not an act, but a habit.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Champions keep playing until they get it right.",
  "It's not whether you get knocked down; it's whether you get up.",
  "The way to get started is to quit talking and begin doing.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is during our darkest moments that we must focus to see the light.",
  "Believe you can and you're halfway there.",
  "The only impossible journey is the one you never begin.",
  "In the midst of difficulty lies opportunity.",
  "Life is what happens to you while you're busy making other plans.",
  "The future belongs to those who prepare for it today.",
  "Yesterday is history, tomorrow is a mystery, today is a gift.",
  "The only way to do great work is to love what you do.",
  "Innovation distinguishes between a leader and a follower.",
  "Stay hungry, stay foolish.",
  "Your time is limited, don't waste it living someone else's life.",
  "The journey of a thousand miles begins with one step.",
  "A goal is a dream with a deadline.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The only person you should try to be better than is who you were yesterday.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only limits that exist are the ones you place on yourself.",
  "You are never too old to set another goal or to dream a new dream.",
  "The expert in anything was once a beginner.",
  "Progress, not perfection.",
  "You don't have to be great to get started, but you have to get started to be great.",
  "Every master was once a disaster.",
  "Fall seven times, stand up eight.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "You can't go back and change the beginning, but you can start where you are and change the ending.",
  "Don't be afraid to give up the good to go for the great.",
  "The biggest risk is not taking any risk.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The cave you fear to enter holds the treasure you seek.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The best revenge is massive success.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.",
  "Experience is a hard teacher because she gives the test first, the lesson afterward.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "What we think, we become.",
  "The mind is everything. What you think you become.",
  "Peace comes from within. Do not seek it without.",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
  "The ultimate measure of a person is not where they stand in moments of comfort and convenience, but where they stand at times of challenge and controversy.",
  "Nothing will work unless you do.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "You are confined only by the walls you build yourself.",
  "Unless you try to do something beyond what you have already mastered, you will never grow.",
  "Life begins at the end of your comfort zone.",
  "Do what you can with all you have, wherever you are.",
  "Be yourself; everyone else is already taken.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "What the mind of person can conceive and believe, it can achieve.",
  "Strive not to be a success, but rather to be of value.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "It's not what happens to you, but how you react to it that matters.",
  "The most common way people give up their power is by thinking they don't have any.",
  "If you do what you've always done, you'll get what you've always gotten.",
  "You take your life in your own hands, and what happens? A terrible thing, no one to blame.",
  "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whether you think you can or you think you can't, you're right.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The only way to do great work is to love what you do.",
  "If life were predictable it would cease to be life, and be without flavor.",
  "If you look at what you have in life, you'll always have more.",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
  "Life is what happens when you're busy making other plans.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is either a daring adventure or nothing at all.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "If life were predictable it would cease to be life and be without flavor.",
  "In order to write about life first you must live it.",
  "The big lesson in life, baby, is never be scared of anyone or anything.",
  "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "Life is really simple, but we insist on making it complicated.",
  "May you live all the days of your life.",
  "Life itself is the most wonderful fairy tale.",
  "Do not let making a living prevent you from making a life.",
  "Life is made of ever so many partings welded together.",
  "Turn your wounds into wisdom.",
  "The way I see it, if you want the rainbow, you gotta put up with the rain.",
  "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
  "Don't settle for what life gives you; make life better and build something.",
  "Everything negative - pressure, challenges - is all an opportunity for me to rise.",
  "I like criticism. It makes you strong.",
  "You never really learn much from hearing yourself speak.",
  "Life imposes things on you that you can't control, but you still have the choice of how you're going to live through this.",
  "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
  "The only courage that matters is the kind that gets you from one moment to the next.",
  "Your problem isn't the problem. Your reaction is the problem.",
  "You can't make positive choices for the rest of your life without an environment that makes those choices easy, natural, and enjoyable.",
  "You are enough just as you are.",
  "Everything you need is inside you.",
  "Your potential is endless.",
  "You are stronger than you think.",
  "Believe in your infinite potential.",
  "You have the power to create change.",
  "Your dreams are valid.",
  "You are capable of amazing things.",
  "Trust the process.",
  "You are exactly where you need to be.",
  "Your journey is unique and beautiful.",
  "You have everything it takes.",
  "You are worth fighting for.",
  "Your story isn't over yet.",
  "You are braver than you believe.",
  "You deserve all the good things.",
  "You are making a difference.",
  "You are loved and appreciated.",
  "You have so much to offer the world.",
  "You are on the right path.",
  "You are growing stronger every day.",
  "You have unlimited potential.",
  "You are exactly who you're meant to be.",
  "You are enough, always have been, always will be.",
  "You have the strength to overcome anything.",
  "You are worthy of love and respect.",
  "You are creating your own path.",
  "You have the power to change your life.",
  "You are destined for greatness.",
  "You are more resilient than you know.",
  "You have what it takes to succeed.",
  "You are capable of incredible growth.",
  "You deserve happiness and peace.",
  "You are writing your own story.",
  "You have the courage to face any challenge.",
  "You are perfectly imperfect.",
  "You have the ability to inspire others.",
  "You are constantly evolving and improving.",
  "You deserve to take up space.",
  "You have unlimited possibilities ahead.",
  "You are worthy of your dreams.",
  "You have the strength to start over.",
  "You are exactly what the world needs.",
  "You have permission to be yourself.",
  "You are capable of healing and growth.",
  "You deserve kindness, especially from yourself.",
  "You have the power to choose your thoughts.",
  "You are worthy of investment in yourself.",
  "You have unique gifts to share.",
  "You are allowed to take breaks.",
  "You have the wisdom to make good choices.",
  "You are worthy of celebrating your wins.",
  "You have the strength to let go of what doesn't serve you.",
  "You are allowed to change your mind.",
  "You have the courage to be vulnerable.",
  "You are worthy of boundaries.",
  "You have the power to forgive yourself.",
  "You are allowed to ask for help.",
  "You have the strength to face your fears.",
  "You are worthy of patience with yourself.",
  "You have the ability to learn from mistakes.",
  "You are allowed to prioritize yourself.",
  "You have the wisdom to trust your intuition.",
  "You are worthy of compassion.",
  "You have the strength to keep going.",
  "You are allowed to feel all your emotions.",
  "You have the power to create boundaries.",
  "You are worthy of rest and relaxation.",
  "You have the courage to speak your truth.",
  "You are allowed to outgrow people and situations.",
  "You have the strength to rebuild.",
  "You are worthy of second chances.",
  "You have the power to choose love over fear.",
  "You are allowed to be proud of your progress.",
  "You have the wisdom to know your worth.",
  "You are worthy of all the love you give to others.",
  "You have the strength to break cycles.",
  "You are allowed to start where you are.",
  "You have the power to transform your life.",
  "You are worthy of grace and forgiveness.",
  "You have the courage to dream big.",
  "You are allowed to take things one day at a time.",
  "You have the strength to overcome any obstacle.",
  "You are worthy of investment and growth.",
  "You have the power to make a difference.",
  "You are allowed to be gentle with yourself.",
  "You have the wisdom to navigate life's challenges.",
  "You are worthy of celebration.",
  "You have the strength to create the life you want.",
  "You are allowed to hope for better days.",
  "You have the power to inspire change.",
  "You are worthy of all good things.",
  "You have the courage to keep trying.",
  "You are allowed to believe in yourself.",
  "You have the strength to rise above.",
  "You are worthy of your own love and respect.",
  "You have the power to make today count.",
  "You are allowed to trust the process.",
  "You have the wisdom to learn and grow.",
  "You are worthy of happiness and fulfillment.",
  "You have the strength to persevere.",
  "You are allowed to be proud of how far you've come.",
  "You have the power to choose your response.",
  "You are worthy of peace and contentment.",
  "You have the courage to face tomorrow.",
  "You are allowed to believe in miracles.",
  "You have the strength to carry on.",
  "You are worthy of all the effort you put in.",
  "You have the power to make things better.",
  "You are allowed to have faith in yourself.",
  "You have the wisdom to make the right choices.",
  "You are worthy of every opportunity that comes your way.",
  "Time to stop making excuses and start making progress.",
  "Your comfort zone is where dreams go to die.",
  "Either you run the day or the day runs you.",
  "Discipline is choosing between what you want now and what you want most."
];

export const HARSH_MOTIVATIONAL_MESSAGES = [
  "Get off your ass and just fucking do it already!",
  "Wakey wakey! Time to get off your fucking ass and grind!",
  "Stop being a lazy piece of shit and hit the gym!",
  "Your excuses are weaker than your last workout!",
  "Quit whining like a little bitch and start grinding!",
  "The only thing worse than failing is not trying at all, you coward!",
  "Stop making excuses and start making gains, dumbass!",
  "Your future self is calling you a lazy fuck right now!",
  "Get up and do something productive instead of rotting away!",
  "Stop being pathetic and start being powerful!",
  "Your goals don't give a shit about your feelings!",
  "Comfort is the enemy of greatness, you soft fuck!",
  "Stop being weak and start being the beast you're meant to be!",
  "Your competition is training while you're making excuses!",
  "Man the fuck up and face your challenges!",
  "Stop being a victim and start being a victor!",
  "Your dreams are calling but you're too busy sleeping!",
  "Mediocrity is a choice, stop choosing it!",
  "Success doesn't give a damn about your comfort zone!",
  "Stop being ordinary when you were born to be extraordinary!",
  "Your potential is wasted on your excuses!",
  "Time to separate yourself from the weak masses!",
  "Champions don't make excuses, they make results!",
  "Your laziness today is tomorrow's regret!",
  "Stop fucking around and start fucking winning!",
  "Pain is temporary, but quitting lasts forever, you quitter!",
  "Your goals are laughing at your lack of effort!",
  "Stop being soft and start getting hard results!",
  "Excellence demands sacrifice, what are you giving up?",
  "Your comfort zone is a prison, break the fuck out!",
  "Winners train, losers complain - which one are you?",
  "Stop talking and start walking the walk!",
  "Your excuses expired a long time ago!",
  "Greatness is earned through blood, sweat, and no tears!",
  "Stop being average, average is for quitters!",
  "Your potential is screaming at you to wake up!",
  "Discipline beats motivation every fucking time!",
  "Stop waiting for perfect and start working with what you have!",
  "Your goals don't care about your mood!",
  "Champions are made when nobody's watching!",
  "Stop being weak-minded and start being strong-willed!",
  "Your future depends on what you do today, not tomorrow!",
  "Stop making wishes and start making it happen!",
  "Excuses will always be there for you, success won't!",
  "Your dreams are tired of waiting for you!",
  "Stop being a spectator and start being a competitor!",
  "Weakness is a choice, stop choosing it!",
  "Your comfort zone is killing your potential!",
  "Stop being scared and start being scarred from hard work!",
  "Champions don't cry, they conquer!",
  "Your excuses are your biggest enemy!",
  "Stop being soft and start being savage!",
  "Success hates lazy people, which side are you on?",
  "Your goals are waiting for you to grow some balls!",
  "Stop being a dreamer and start being a doer!",
  "Mediocrity is contagious, stop spreading it!",
  "Your potential is being murdered by your comfort!",
  "Stop being weak and start being relentless!",
  "Champions don't have time for your bullshit excuses!",
  "Your comfort zone is where ambition goes to die!",
  "Stop being ordinary when extraordinary is an option!",
  "Your dreams don't work unless you do, lazy ass!",
  "Stop making excuses and start making history!",
  "Weakness is a mindset, change your fucking mind!",
  "Your goals are bigger than your excuses!",
  "Stop being a passenger and start driving your life!",
  "Champions are forged in fire, not comfort!",
  "Your potential is rotting away with every excuse!",
  "Stop being soft and start being unstoppable!",
  "Success doesn't recognize participation trophies!",
  "Your dreams are calling, stop sending them to voicemail!",
  "Stop being weak-willed and start being warrior-minded!",
  "Champions don't make excuses, they make miracles!",
  "Your comfort zone is a luxury you can't afford!",
  "Stop being average and start being savage!",
  "Excuses are tools of the incompetent!",
  "Your potential is suffocating under your comfort!",
  "Stop being a quitter and start being a fighter!",
  "Champions don't whine, they grind!",
  "Your goals are tired of your half-ass efforts!",
  "Stop being soft and start being solid!",
  "Success is allergic to comfort zones!",
  "Your dreams are dying while you're sleeping!",
  "Stop making excuses and start making moves!",
  "Weakness is temporary if you choose strength!",
  "Your potential is screaming for action!",
  "Stop being ordinary, ordinary is overrated!",
  "Champions don't have comfort zones!",
  "Your excuses are weaker than your willpower should be!",
  "Stop being soft and start being steel!",
  "Success doesn't give a fuck about your feelings!",
  "Your goals are waiting for you to stop being a bitch!",
  "Stop making wishes and start making war on mediocrity!",
  "Champions don't make excuses, they make statements!",
  "Your comfort zone is the enemy of your potential!",
  "Stop being weak and start being a weapon of mass improvement!",
  "Excuses are for people who don't want it bad enough!",
  "Your dreams are tired of your procrastination!",
  "Stop being soft and start being savage as fuck!",
  "Success hates comfortable people!",
  "Your potential is being wasted on comfort!",
  "Stop being ordinary when you can be extraordinary!",
  "Champions don't make excuses, they make examples!",
  "Your goals don't give a shit about your comfort!",
  "Stop being weak-minded and start being warrior-hearted!",
  "Comfort is the slow death of ambition!",
  "Your dreams are calling, stop being afraid to answer!",
  "Stop making excuses and start making progress!",
  "Champions are built through struggle, not comfort!",
  "Your potential is buried under your excuses!",
  "Stop being soft and start being ruthless with your goals!",
  "Success doesn't negotiate with comfort zones!",
  "Your dreams are waiting for you to grow up!",
  "Stop being average and start being awesome!",
  "Champions don't have time for comfort!",
  "Your excuses are the only thing standing between you and success!",
  "Stop being weak and start being relentless as hell!",
  "Comfort zones are where dreams go to die slow deaths!",
  "Your potential is screaming at you to wake the fuck up!",
  "Stop making excuses and start making it count!",
  "Champions don't comfort themselves with excuses!",
  "Your goals are bigger than your bullshit!",
  "Stop being soft and start being a success story!",
  "Weakness is a choice you keep making!",
  "Your dreams don't care about your comfort!",
  "Stop being ordinary, be extra-fucking-ordinary!",
  "Champions don't make room for excuses!",
  "Your potential is dying a slow death in your comfort zone!",
  "Stop being weak and start being worth it!",
  "Success doesn't shake hands with comfortable people!",
  "Your goals are laughing at your weak-ass efforts!",
  "Stop making excuses and start making magic happen!",
  "Champions are carved from discomfort!",
  "Your comfort zone is a prison you built yourself!",
  "Stop being soft and start being spectacular!",
  "Excuses are the nails used to build a house of failure!",
  "Your dreams are tired of your weak-ass commitment!",
  "Stop being average when you were born to be amazing!",
  "Champions don't know what comfort zones are!",
  "Your potential is rotting in your comfort zone!",
  "Stop being weak and start being worth remembering!",
  "Success only visits people who leave their comfort zones!",
  "Your goals are waiting for you to stop being a pussy!",
  "Stop making wishes and start making waves!",
  "Champions don't make excuses, they make legends!",
  "Your comfort zone is where greatness goes to die!",
  "Stop being soft and start being someone who matters!",
  "Weakness is a habit you need to break!",
  "Your dreams are calling but you keep hanging up!",
  "Stop being ordinary when you can be outstanding!",
  "Champions don't comfort themselves, they challenge themselves!",
  "Your potential is suffocating under your comfort blanket!",
  "Stop being weak and start being world-class!",
  "Success doesn't visit comfortable addresses!",
  "Your goals are tired of waiting for you to get serious!",
  "Stop making excuses and start making your mark!",
  "Champions are forged in the fire of discomfort!",
  "Your comfort zone is the graveyard of your potential!",
  "Stop being soft and start being the standard!",
  "Excuses are the enemy of excellence!",
  "Your dreams are dying while you're making excuses!",
  "Stop being average and start being unstoppable!",
  "Champions don't have comfortable lives!",
  "Your potential is screaming for you to act!",
  "Stop being weak and start being legendary!",
  "Success is allergic to your comfort zone!",
  "Your goals don't give a damn about your comfort!",
  "Stop making wishes and start making it happen now!",
  "Champions don't make excuses, they make history!",
  "Your comfort zone is killing your dreams slowly!",
  "Stop being soft and start being significant!",
  "Weakness is just strength that's been lazy!",
  "Your dreams are waiting for you to get off your ass!",
  "Stop being ordinary when extraordinary is waiting!",
  "Champions don't negotiate with comfort!",
  "Your potential is being murdered by your mediocrity!",
  "Stop being weak and start being worth talking about!",
  "Success doesn't recognize comfort zone citizens!",
  "Your goals are bigger than your fear of discomfort!",
  "Stop making excuses and start making memories!",
  "Champions are built when comfort is abandoned!",
  "Your comfort zone is where ambition goes to retire!",
  "Stop being soft and start being spectacular as fuck!",
  "Excuses are just fear wearing a disguise!",
  "Your dreams are tired of your half-hearted attempts!",
  "Stop being average when you can be absolutely incredible!",
  "Champions don't live in comfort zones!",
  "Your potential is wasting away in comfort!",
  "Stop being weak and start being wonderful!",
  "Success only dates people who've left their comfort zones!",
  "Your goals are waiting for you to stop being scared!",
  "Stop making wishes and start making war on weakness!",
  "Champions don't make excuses, they make magic!",
  "Your comfort zone is the death of your dreams!",
  "Stop being soft and start being something special!",
  "Weakness is just unrealized strength!",
  "Your dreams are calling but you're too comfortable to answer!",
  "Stop being ordinary when you were designed to be outstanding!",
  "Champions don't comfort themselves with mediocrity!",
  "Your potential is screaming at you to stop being comfortable!",
  "Stop being weak and start being world-changing!",
  "Success doesn't shake hands with comfortable people!",
  "Your goals are laughing at your comfort zone!",
  "Stop making excuses and start making miracles!",
  "Champions are carved from the stone of discomfort!",
  "Your comfort zone is where greatness goes to suffocate!",
  "Stop being soft and start being absolutely savage!",
  "Excuses are the currency of the unsuccessful!",
  "Your dreams are dying a slow death in your comfort zone!",
  "Stop being average and start being absolutely amazing!",
  "Champions don't know what comfort feels like!",
  "Your potential is rotting away in comfort!",
  "Stop being weak and start being worth celebrating!",
  "Success is a stranger to comfortable people!",
  "Your goals are tired of your comfortable bullshit!",
  "Stop making wishes and start making war on mediocrity!",
  "Champions don't make excuses, they make excellence!",
  "Your comfort zone is the cemetery of your potential!",
  "Stop being soft and start being absolutely outstanding!",
  "Weakness is just strength taking a permanent vacation!",
  "Your dreams are calling but you're too comfortable to move!",
  "Stop being ordinary when you can be absolutely extraordinary!",
  "Champions don't have comfortable relationships with failure!",
  "Your potential is suffocating under layers of comfort!",
  "Stop being weak and start being absolutely wonderful!",
  "Success doesn't visit comfortable neighborhoods!",
  "Your goals are waiting for you to abandon comfort!",
  "Stop making excuses and start making absolute magic!",
  "Champions are forged in the flames of absolute discomfort!",
  "Your comfort zone is where dreams go to die permanently!",
  "Stop being soft and start being absolutely spectacular!",
  "Excuses are just fear dressed up in fancy clothes!",
  "Your dreams are tired of your absolutely pathetic efforts!",
  "Stop being average when you were born to be absolutely incredible!",
  "Champions don't make their homes in comfort zones!",
  "Your potential is absolutely wasting away in comfort!",
  "Stop being weak and start being absolutely worth it!",
  "Success is absolutely allergic to comfortable people!",
  "Your goals are absolutely tired of waiting for you!",
  "Stop making wishes and start making absolutely everything happen!",
  "Champions don't make excuses, they make absolutely everything count!",
  "Your comfort zone is the absolute death of everything great in you!",
  "Stop being soft and start being absolutely everything you're meant to be!"
];

export class NotificationService {
  private static instance: NotificationService;
  private hasPermission = false;
  private lastAppOpen = Date.now();

  private constructor() {}

  static getInstance(): NotificationService {
    if (!NotificationService.instance) {
      NotificationService.instance = new NotificationService();
    }
    return NotificationService.instance;
  }

  async requestPermissions(): Promise<boolean> {
    if (!Capacitor.isNativePlatform()) {
      console.log('Not running on native platform, notifications not available');
      return false;
    }

    try {
      const permission = await LocalNotifications.requestPermissions();
      this.hasPermission = permission.display === 'granted';
      return this.hasPermission;
    } catch (error) {
      console.error('Failed to request notification permissions:', error);
      return false;
    }
  }

  updateLastAppOpen(): void {
    this.lastAppOpen = Date.now();
    localStorage.setItem('lastAppOpen', this.lastAppOpen.toString());
  }

  private getLastAppOpen(): number {
    const stored = localStorage.getItem('lastAppOpen');
    return stored ? parseInt(stored) : Date.now();
  }

  private shouldSendNotification(): boolean {
    const lastOpen = this.getLastAppOpen();
    const twoDaysAgo = Date.now() - (2 * 24 * 60 * 60 * 1000);
    return lastOpen < twoDaysAgo;
  }

  private getRandomMessage(isHarsh: boolean): string {
    const messages = isHarsh ? HARSH_MOTIVATIONAL_MESSAGES : MOTIVATIONAL_MESSAGES;
    const randomIndex = Math.floor(Math.random() * messages.length);
    return messages[randomIndex];
  }

  async scheduleMotivationalNotification(isHarsh: boolean = false): Promise<void> {
    if (!this.hasPermission || !Capacitor.isNativePlatform()) {
      return;
    }

    if (!this.shouldSendNotification()) {
      return;
    }

    try {
      const message = this.getRandomMessage(isHarsh);
      
      await LocalNotifications.schedule({
        notifications: [
          {
            title: "Time to Get Back in There!",
            body: message,
            id: Date.now(),
            schedule: { at: new Date(Date.now() + 1000) }, // 1 second from now for testing
            sound: 'beep.wav',
            attachments: undefined,
            actionTypeId: "",
            extra: null
          }
        ]
      });
    } catch (error) {
      console.error('Failed to schedule notification:', error);
    }
  }

  startMotivationalReminders(isEnabled: boolean, isHarsh: boolean = false): void {
    if (!isEnabled) {
      return;
    }

    // Check every hour if we should send a notification
    setInterval(() => {
      this.scheduleMotivationalNotification(isHarsh);
    }, 60 * 60 * 1000); // 1 hour
  }
}
